version: 2.1

commands:
  connect-remote:
    steps:
      - add_ssh_keys:
          fingerprints:
            - SHA256:O76UEgd4JGePYnipLYEhyK0UXrsuT1cbgZLcobR3GIM
      - run:
          name: Connect to remote machine
          command: |
            systemctl start docker && ssh -o StrictHostKeyChecking=no root@45.61.58.231 "exit"
  use-remote-context:
    steps:
      - add_ssh_keys:
          fingerprints:
            - "SHA256:O76UEgd4JGePYnipLYEhyK0UXrsuT1cbgZLcobR3GIM"
      - run:
          name: Check and create Docker context
          command: |
            if docker context ls --format '{{.Name}}' | grep -q "remote"; then
              echo "Docker context already exists."
            else
              echo "Docker context 'remote' does not exist. Creating..."
              docker context create remote --docker "host=ssh://root@45.61.58.231"
            fi
            echo "Context created" && docker context ls && docker context use remote && docker info

  build-and-run-image:
    steps:
      - add_ssh_keys:
          fingerprints:
            - "SHA256:O76UEgd4JGePYnipLYEhyK0UXrsuT1cbgZLcobR3GIM"
      - checkout
      - run:
          name: Build a docker image from Dockerfile
          command: |
            docker build --no-cache -t askturing-image:${CIRCLE_SHA1} .

  start-server:
    parameters:
      server-type:
        type: enum
        enum: ["staging", "production"]
        default: staging
        description: We will be running 2 different types of servers
      server-port:
        type: integer
        default: 3001
        description: Staging server will use port 3001 and production will use 3000
    steps:
      - add_ssh_keys:
          fingerprints:
            - "SHA256:O76UEgd4JGePYnipLYEhyK0UXrsuT1cbgZLcobR3GIM"
      - run:
          name: Start the server on the remote machine
          command: |
            docker context use remote && docker stop askturing-<< parameters.server-type >>-container || true && \
            docker rm askturing-<< parameters.server-type >>-container || true && \
            docker run -d --name askturing-<< parameters.server-type >>-container \
            -p << parameters.server-port >>:<< parameters.server-port >> askturing-image:${CIRCLE_SHA1}

jobs:
  Deploy-Staging-Server:
    docker:
      - image: cimg/base:2022.09
    steps:
      - connect-remote
      - build-and-run-image
      - use-remote-context
      - start-server:
          server-type: "staging"
          server-port: 3001

  Deploy-Production-Server:
    docker:
      - image: cimg/base:2022.09
    steps:
      - connect-remote
      - build-and-run-image
      - use-remote-context
      - start-server:
          server-type: "production"
          server-port: 3000

workflows:
  askturing-deployment-workflow:
    jobs:
      - Deploy-Staging-Server
      - Deploy-Production-Server:
          type: approval
          requires:
            - Deploy-Staging-Server
